org: aimbere
app: user-service
service: user-service

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x

package:
  individually: true
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-linux-arm64-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'

build:
  esbuild:
    bundle: true
    minify: true
    external:
      - '@aws-sdk/client-s3'
      - 'dotenv'
      - 'jsonwebtoken'
      - 'class-validator'
      - '@prisma/client'
      - 'resend'


    exclude:
      - '@aws-sdk/*'
    packages: external
    buildConcurrency: 3
    sourcemap:
      type: linked
      setNodeOptions: true

functions:
  signup:
    handler: app/handler.signup
    events:
      - httpApi:
          path: /signup
          method: post
    
  login:
    handler: app/handler.login
    events:
      - httpApi: 
          path: /login
          method: post
  
  verify:
    handler: app/handler.verify
    events:
      - httpApi: 
          path: /verify
          method: post
  
  profile:
    handler: app/handler.profile
    events:
      - httpApi: 
          path: /user
          method: get
      - httpApi:
          path: /user
          method: put
      - httpApi:
          path: /user
          method: post
